### ISSUE TITLE
strange result from running the example in the package

### ISSUE THREAD

**Issue by githubfun** [s-u/fasttime#2]
` identical(a, b)` evaluates to false when I increase the length of `ts` to a relative large number.

```
> ## let us generate a bunch of random timestamps until today
> ts <- as.character(.POSIXct(runif(5e4) * unclass(Sys.time())))

> ## convert them using as.POSIXct
> system.time(a <- as.POSIXct(ts, "GMT"))
   user  system elapsed 
  0.088   0.000   0.087 

> ## same using the fast method
> system.time(b <- fastPOSIXct(ts, "GMT"))
   user  system elapsed 
  0.004   0.000   0.005 

> identical(a, b)
[1] FALSE
```

**Comment by s-u** [comment]
Thanks, this will only happen in time zones west of GMT. if you look at the entries that are different (where `fasttime)` returns `NA`), they are negative, i.e. before `1970-01-01 GMT` - thus unsupported by `fasttime`. The the bug is really that the example should explicitly set the timezone to `GMT` to make sure resulting times are not before `1970-01-01 GMT`:

```r
ts <- as.character(.POSIXct(runif(5e4) * unclass(Sys.time()), "GMT"))
```

I'll fix the example accordingly, fortunately this is not an issue with `fastPOSIXct` itself.

**Comment by githubfun** [comment]
Thanks a lot!
